# Note: remember to `git submodule update --recursive` to pull in dependencies
[profile.default]
src='src'
broadcast='broadcast'
script='script'
test='test'
out='out'
libs=['lib']
cache_path='cache'
fs_permissions = [{ access = "read-write", path = "./addresses/"}]
solc_version="0.8.17"
ffi=true
# optimizer=true
# optimizer_runs=20000

# Private keys are expected to be of the form <NETWORK>_PRIVATE_KEY
# The relevant code is in Deployer.sol
[rpc_endpoints]
polygon="${POLYGON_NODE_URL}"
mumbai="${MUMBAI_NODE_URL}"
[etherscan]
mumbai={key="${POLYGON_API_KEY}"}

# The remappings are in remappings.txt so vscode solidity ext. can read them
# The first lines are the manual remappings
# The other lines are a copy/paste of the inferred mappings shown by `forge config` (inferred from imported libs)
# You should update remappings.txt whenever a lib change impacts remappings
[fmt]
tab_width=2
int_types="short"
number_underscores="thousands"
ignore = ['lib/**/*.sol','**/vendor/**/*.sol','**/preprocessed/**/*.sol']