# Note: remember to `git submodule update --recursive` to pull in dependencies
[profile.default]
src='src'
broadcast='broadcast'
script='script'
test='test'
out='out'
libs=['lib']
cache_path='cache'
evm_version='paris'
fs_permissions = [{ access = "read-write", path = "./addresses/"}, { access = "read-write", path = "./analytics/"}, { access = "read", path = "./out/" }, { access = "read", path = "mgvConfig.json" }]
solc_version="0.8.20"
ffi=true
optimizer=false

# test ratios
[profile.test-ratios]
test='test-ratios'
fs_permissions = [{ access = "read-write", path = "./test-ratios/"}, { access = "read-write", path = "./analytics/"}, { access = "read", path = "./out/" }, { access = "read", path = "mgvConfig.json" }]

# via_ir=true
# optimizer_runs=200

# Private keys are expected to be of the form <NETWORK>_PRIVATE_KEY
# The relevant code is in Deployer.sol
[rpc_endpoints]
polygon="${POLYGON_NODE_URL}"
mumbai="${MUMBAI_NODE_URL}"
ethereum="${ETHEREUM_NODE_URL}"
testnet_zkevm="https://rpc.public.zkevm-test.net"
zkevm="https://zkevm-rpc.com"
goerli="${GOERLI_NODE_URL}"
arbitrum="${ARBITRUM_NODE_URL}"

[etherscan]
goerli={key="${GOERLI_API_KEY}"}
mumbai={key="${POLYGON_API_KEY}"}
polygon={key="${POLYGON_API_KEY}"}
testnet_zkevm={key="${ZKEVM_API_KEY}",chain=1442,url="https://api-testnet-zkevm.polygonscan.com/api"}
zkevm={key="${ZKEVM_API_KEY}",chain=1101,url="https://api-zkevm.polygonscan.com/api"}
arbitrum={key="${ARBITRUM_API_KEY}"}

# The remappings are in remappings.txt so vscode solidity ext. can read them
# The first lines are the manual remappings
# The other lines are a copy/paste of the inferred mappings shown by `forge config` (inferred from imported libs)
# You should update remappings.txt whenever a lib change impacts remappings
[fmt]
tab_width=2
int_types="short"
number_underscores="thousands"
ignore = ['lib/**/*.sol','**/vendor/**/*.sol','**/preprocessed/**/*.sol']

# If you use scripts from this repo but don't want to set/use config fields that
# depend on environment variables, set FOUNDRY_PROFILE=no_env_vars. It's not
# necessary to reset the [rpc_endpoints] section since it's lazily loaded.
[profile.no_env_vars.etherscan]
mumbai={key=""}
polygon={key=""}
goerli={key=""}
testnet_zkevm={key="",chain=1442,url="https://api-testnet-zkevm.polygonscan.com/api"}
zkevm={key="",chain=1101,url="https://api-zkevm.polygonscan.com/api"}
arbitrum={key=""}
