# Publishes npm package with a version bump chosen by the user.
# 
# From the master branch, package bumps can be patch, minor, or major.
#
# From the develop branch, package bumps can only be prerelease
name: "Publish npm package"

description: "Publish"


runs:
  using: composite
  steps:
     -  name: "Publish"
        uses: mangrovedao/.github/.github/workflows/reusable-publish-npm-package.yml@master
        with:
          versionBumpStrategy: $VERSION_BUMP_STRATEGY

