# Publishes npm package with a version bump chosen by the user.
# 
# From the master branch, package bumps can be patch, minor, or major.
#
# From the develop branch, package bumps can only be prerelease
name: "Publish npm package"

on:
  workflow_call:
    inputs:
      versionBumpStrategy:
        description: 'version bump strategy'
        required: true
    secrets:
      BOT_GH_PAT_TOKEN:
        required: true
      BOT_NPM_TOKEN:
        required: true
      BOT_GPG_PRIVATE_KEY:
        required: true
      BOT_GPG_PASSPHRASE:
        required: true


jobs:
  call-reusable-workflow:
    name: "Publish"
    uses: mangrovedao/.github/.github/workflows/reusable-publish-npm-package.yml@master
    with:
      versionBumpStrategy: ${{ inputs.versionBumpStrategy }}
    secrets:
      BOT_GH_PAT_TOKEN: ${{ secrets.BOT_GH_PAT_TOKEN }}
      BOT_NPM_TOKEN: ${{ secrets.BOT_NPM_TOKEN }}
      BOT_GPG_PRIVATE_KEY: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
      BOT_GPG_PASSPHRASE: ${{ secrets.BOT_GPG_PASSPHRASE }}
