# Publishes npm package with a version bump chosen by the user.
# 
# From the master branch, package bumps can be patch, minor, or major.
#
# From the develop branch, package bumps can only be prerelease
name: "Publish npm package"

on:
  workflow_dispatch:
    inputs:
      versionBumpStrategy:
        description: 'Version bump strategy'
        required: true
        default: 'prerelease'
        type: choice
        options:
        - test
        - prerelease
        - patch
        - minor
        - major

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Foundry Setup
      uses: ./.github/actions/foundry-setup

    - name: "Publish"
      uses: ./.github/actions/publish-npm-package
      with: |
        versionBumpStrategy: ${{ github.event.inputs.versionBumpStrategy }}

      

